[Hardware.Components.Bus]
Name = 'Bus'
Note = 'An electronic pathway through which data can be transferred'

[Hardware.Components.Bus.North]
Name = 'North Bridge Chipset Bus'
Note = 'The north bridge is the area of the motherboard that contains the major computational components. The northbridge chipset buses are buses that are used within the north bridge'
Comment = ''

[Hardware.Components.Bus.North.Front]
Name = 'Front Side Bus'
Note = 'Connecting the CPU and the north bridged together'
Comment = ''

[Hardware.Components.Bus.North.Graphics]
Name = 'High Speed Graphics Bus'
Note = 'Connects the GPU with the northbridge'
Comment = ''

[Hardware.Components.Bus.North.MBUS]
Name = 'Memory Bus'
Note = 'Connects the north bridge to the RAM'
Comment = ''

[Hardware.Components.Bus.South]
Name = 'South Bridge Chipset Bus'
Note = 'Buses that connect to the south bridge'
Comment = ''

[Hardware.Components.Bus.South.DMI]
Name = 'Direct media interface'
Note = 'Connects the north and south bridge together'
Comment = ''

# End of North and South Bridge Chipset Bus

[Hardware.Components.Bus.USB]
Name = 'Universal Serial Bus'
Note = 'A widely used bus standard for connecting peripherals. It is a versatile and easy-to-use interface that has become ubiquitous in modern computing. USB has evolved over several generations, offering increasing speeds and capabilities'
Comment = 'Used for keyboards, mice, printers, flash drives, external storage devices'

[Hardware.Components.Bus.USB.2]
Name = 'Version'
Note = 'Older method of USB'
Comment = ''

[Hardware.Components.Bus.USB.3]
Name = 'Version 3 and 3.1'
Note = 'Compatible with USB 2 ports. The most modern version and fastest transfer rates, colored blue to indicate its version 3'
Comment = ''

[Hardware.Components.Bus.USB.USBA]
Name = 'Type A'
Note = 'Most common bus standard but it is being seceded by type c'
Comment = ''

[Hardware.Components.Bus.USB.USBB]
Name = 'Type B'
Note = 'Mostly used for larger devices like printers and is still used quite often'
Comment = ''

[Hardware.Components.Bus.USB.USBB_Mini_Micro]
Name = 'Type B Mini And Micro'
Note = 'Not used that often'
Comment = ''

[Hardware.Components.Bus.USB.USBC]
Name = "USB Type C"
Note = 'Most modern method ot connect external devices and can be used for transporting data and power transmission, it can also be flipped either way to terminate it'
Comment = ''

# end of USB

[Hardware.Components.Bus.Lighting]
Name = 'Lighting Port'
Note = 'Used by and for Apple devices only'
Comment = 'This is starting to become phased out because of regulations requiring USBC as the standard. That and the consumers prefer USBC over lighting'

[Hardware.Components.Bus.Thunderbolt]
Name = 'Thunderbolt'
Note = 'A high-speed serial bus standard made by apple that combines the features of PCIe and DisplayPort. It offers even faster data transfer rates than FireWire, making it suitable for connecting external graphics cards, high-performance storage devices, and docking stations'
Comment = 'Used for external graphics cards, high-performance storage devices, docking stations'

[Hardware.Components.Bus.SATA]
Name = 'Serial Advanced Technology Attachment'
Note = 'A serial interface for connecting storage devices. It offers faster data transfer rates and hot-swapping capabilities than its predecessor, PATA/IDE'
Comment = 'Hard drives, SSDs'
Measurement = 'Up to 300 MB/s | 7 pins | 1 device per cable (channel) | sometimes power over cable if it does not it uses Molex'

[Hardware.Components.Bus.IDE]
Name = 'Integrated Drive Electronics'
Note = 'Aka PATA, an older parallel bus standard for connecting storage devices. It was once the most common interface for connecting storage devices, but it has been largely supplanted by SATA due to its limitations in speed and scalability. It was used for hard drives, optical drives. You can have up to two devices using Pata, a device can either be the master or the slave (also called primary and secondary). The priority status of the drive can be configured by either covering or closing a set of pins set on the drive'
Comment = ''
Measurement = 'Up to 133 Mb/s | 40 pin cable | 2 devices per cable | commonly BERG power or Molex, sometimes an all in one PATA connector doing power and data'

[Hardware.Components.Bus.PCIE]
Name = 'Peripheral Component Interconnect Express'
Note = 'A high-speed serial bus standard for expansion cards. It offers faster data transfer rates than its predecessor, PCI, and is the most common bus standard for connecting high-performance devices'
applications = 'Graphics cards, sound cards, network adapters, storage controllers'
Comment = ''
width = 'Serial, 1 - 16 full duplex lanes'

[Hardware.Components.Bus.PCI]
Name = 'Peripheral Component Interconnect'
Note = 'Older of PCIE'
Comment = ''
width = '32 bit'

[Hardware.Components.Bus.AGP]
Name = 'Accelerated graphics port'
Note = 'Used for graphic cards'
Comment = ''
Measurement = '32 bit'

[Hardware.Components.Bus.ISA]
Name = 'Industry Standard Architecture'
Note = 'Very old expansion slot, not used anymore'
Comment = ''

[Hardware.Components.Bus.AMR]
Name = "Audio Modem Riser"
Note = 'Used for processing sounds, including sounds that can be produced by modems'
Comment = ''

[Hardware.Components.Bus.PCMCIA]
Name = 'Personal Computer Memory Card International Association'
Note = 'Outdated model commonly used and could fit on the side of a laptop replaced by the USB'
Comment = ''

[Hardware.Components.Bus.DVI]
Name = 'Digital Visual Interface'
Note = 'Usually colored white, used for monitor graphics'
Comment = ''

[Hardware.Components.Bus.HDMI]
Name = 'High-Definition Multimedia Interface'
Note = 'Used for hd video and audio'
Comment = ''

[Hardware.Components.Bus.HDMI.Mini]
Name = 'High-Definition Multimedia Interface Mini'
Note = 'Used for hd video but not audio'
Comment = ''

[Hardware.Components.Bus.Display_Port]
Name = 'Display Port'
Note = 'Another standard that is used for video because HDMI requires a royalty to be payed and display port does not'
Comment = 'Used because HDMI requires a royalty to be payed and display port does not'

[Hardware.Components.Bus.Optical_Audio]
Name = 'Optical audio'
Note = 'Digital instead of analog data to transmit audio information'
Comment = ''

[Hardware.Components.Bus.eSATA]
Name = 'External SATA'
Note = 'A way to hook up an external hard drive'
Comment = ''

[Hardware.Components.Bus.SCSI]
Name = 'Small Computer System Interface'
Note = 'A high-performance bus standard for connecting storage devices and other peripherals. It offers faster data transfer rates and more advanced features than IDE or SATA, making it well-suited for demanding applications like video editing and scientific computing. Because you can fit up to 16 devices each device will get its own address assigned by the computer'
Comment = 'Used for storage devices, RAID arrays, high-performance peripherals. Because you can fit up to 16 devices each device will get its own address assigned by the computer'

[Hardware.Components.Bus.FireWire]
Name = 'FireWire'
Note = 'A high-bandwidth bus standard for connecting digital video cameras and other peripherals. It offers high data transfer rates and low latency, making it ideal for real-time applications like video capture and editing'
Comment = 'Used for digital video cameras, high-performance peripherals'

# End of Bus